runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /process/project
  script: process_project.php
  login: admin
- url: /process/task
  script: process_task.php
  login: admin
- url: /process/subtask
  script: process_subtask.php
  login: admin
- url: /process/attachment
  script: process_attachment.php
  login: admin
- url: /process/complete
  script: process_complete.php
  login: admin
- url: /auth
  script: auth.php
- url: /deauth
  script: deauth.php
- url: /
  script: index.php
# All URLs ending in .gif .png or .jpg are treated as paths to static files in
# the static/ directory. The URL pattern is a regexp, with a grouping that is
# inserted into the path to the file.
- url: /(.*\.(gif|png|jpg|ico|css|js|txt))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|ico|css|js|txt)$

# Map the acme folder for letsencrypt
- url: /\.well-known/acme-challenge/(.*)$
  static_files: acme/\1
  upload: acme/.*
